<% header(name + ' 1.3 Release Notes') %>

<p><% name %> version 1.3 pre-released on 12/DD/20</p>


<a id="MajorChanges"></a><h2>Major Changes</h2>
<ul>
  <li>The Codebase was migrated to Python 3 and pre-released after all Tests passed.</li>
  <li>Firebase Adapter included, see below. THe major change here is the setteling of "reserved sql keywords"</li>
  <li>Maintenance Strategy is to release bugfixes for Python 3 only.</li>
  
</ul>

<a id="NewFeatures"></a><h2>New Features</h2>
<ul>
  <li>Included an existing Firebase 2 Adapter (via kinterbasdb). This one also levelled to fdb and python 3.</li>
</ul>


<a id="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
  
</ul>

<% footer() %>
